### ISSUE TITLE
Not an editor command: SftpSend

### ISSUE THREAD

**Issue by moonvent** [dcampos/nvim-sftp-sync#2]
Hi! Today I try install your plugin, but after install and setup reqs (install in python pysftp and pynvim) I get this error:  

`Not an editor command: SftpSend`

I use neovim 8 with lua (if more detail I use astronvim last version)

Can you help me, please?

**Comment by dcampos** [comment]
You need to run `:UpdateRemotePlugins` after you install/update the plugin.

Using vim-plug, the easiest way is to set it up like this:

```
Plug 'dcampos/nvim-sftp-sync', { 'do': ':UpdateRemotePlugins' }
```

Using packer:

```
use { 'dcampos/nvim-sftp-sync', run = ':UpdateRemotePlugins' }
```

I don't know much about AstroNvim, but from what I've seen it uses packer.

**Comment by moonvent** [comment]
But my neovim base on Lua =(  Sorry, I just choise other lib for this =(

**Comment by dcampos** [comment]
> But my neovim base on Lua =(

Mine too. You just have to call `:UpdateRemotePlugins`, it's a Neovim built-in command, it doesn't matter if your config is Lua or Vimscript based.

> Sorry, I just choise other lib for this =(

No problem. Good luck!
