### ISSUE TITLE
Bug: Windows Path

### ISSUE THREAD

**Issue by MaulanaMalikS** [dcampos/nvim-sftp-sync#3]
Hello!
I am using Windows, and my remote server using Linux. When i push file in directory, the directory path becoming file in server, and don't go inside servers directory, for example:
`index.php` inside `foo\baar` becoming file `foo\baar\index.php` (this is a file name) in the server.

I think it's because the difference of directory path, between my server forwardslash (`/`) and my local backslash (`\`) of directory path.
Thank you!

**Comment by dcampos** [comment]
Thanks for reporting! I just pushed a change that should fix it, please try it out and let me know if something goes wrong.

**Comment by MaulanaMalikS** [comment]
Now it works!
Thank you for the update.
