### ISSUE TITLE
SftpSend is not available.

### ISSUE THREAD

**Issue by ivanzavalin** [dcampos/nvim-sftp-sync#6]
Hi. I've installed the plugin, but the command :SftpSend is not aviable when I try to call it, as well as other commands. The help info is available though.

**Comment by dcampos** [comment]
Hi!

You need to call `:UpdateRemotePlugins` somewhere in your setup, like is mentioned in the README file.

If you're using lazy.nvim, you need something like this:

```
    {
        'dcampos/nvim-sftp-sync',
        build = ':UpdateRemotePlugins',
    },
```

**Comment by ivanzavalin** [comment]
Hi! Thanks for resolving issue. I now try using the plugin but I am getting now this sort of error when trying to send file to a server. Can you suggest what can I do in this case?
![Screenshot from 2023-11-09 10-45-58](https://github.com/dcampos/nvim-sftp-sync/assets/96178318/59dfaf71-a7f6-4d33-a8d6-c75b9ac43118)
